version: "3"

services:

  generate-delivery-management:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/msa-ez/gpt-engineer:v2024022501
#    command: ["-sh"]
    volumes:
      - .:/project
